BaseURL: "http://node-dependency.pedroassis.com.br"
LanguageCode: "en-us"
Title: "Node-Dependency"
Theme: "beg"
disqusShortname: "nodedependency"

Params:
  Author: "Pedro Assis"
  DateForm: "Mon, 2 Jan, 2006"
  GoogleAnalyticsUserID: "UA-64787564-1"
  Github: "pedroassis/node-dependency"
  ShowRelatedPost: True
  Disqus: "nodedependency"
  SyntaxHighlightTheme: "github.min.css"
  highlight : "monokai_sublime"

Indexes:
  tag: "tags"

MetadataFormat: "yaml"