BaseUrl: "http://pedroassis.github.io/node-dependency/"
LanguageCode: "en-us"
Title: "Node-Dependency"
Theme: "hugo_theme_beg"
disqusShortname: "nodedependency"
publishdir: "public"

Params:
  Author: "Pedro Assis"
  DateForm: "Mon, 2 Jan, 2006"
  GoogleAnalyticsUserID: "UA-55005303-5"
  Github: "pedroassis"
  ShowRelatedPost: True
  Disqus: "nodedependency"
  SyntaxHighlightTheme: "github.min.css"

Indexes:
  tag: "tags"

MetadataFormat: "yaml"