BaseURL: "http://node-dependency.pedroassis.com.br/"
LanguageCode: "en-us"
Title: "Node-Dependency"
Theme: "nofancy"
disqusShortname: "nodedependency"

Author:
  name: "Pedro Assis"
  github: "pedroassis/node-dependency"
  linkedin : "https://br.linkedin.com/in/pedroassisbh"
  email : "pedro@pedroassis.com.br"
  gaID: "U2FsdGVkX1/9RsFb+lMIQra9k1D0jGZXb46rJrc/Z60="
  gaKey : "4d657373616765"
  facebook : "https://www.facebook.com/profile.php?id=100005981446817"

Params:
  Author: "Pedro Assis"
  DateForm: "Mon, 2 Jan, 2006"
  GoogleAnalyticsUserID: "UA-64787564-1"
  Github: "pedroassis/node-dependency"
  ShowRelatedPost: True
  disqusShortname: "nodedependency"
  SyntaxHighlightTheme: "github.min.css"
  highlight : "monokai_sublime"

Indexes:
  tag: "tags"

MetadataFormat: "yaml"